name: cd
on:
  push:
    branches: main
    tags: '*'
jobs:
  ci:
    name: Install, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2.1.3
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - name: Install packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm run test:unit
      - name: Integration Test
        run: npm run test:integration

  publish-npm:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - name: Install packages
        run: npm i
      - name: Publish (NPM)
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - name: Install packages
        run: npm i
      - name: Publish (GitHub)
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
