name: ci
on: [push, pull_request]
env:
  WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2.1.3
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - name: Install packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm run test:unit
      - name: Integration Test
        run: npm run test:integration
      - name: Success
        if: ${{success()}}
        run: |
          wget https://raw.githubusercontent.com/chronoDave/user-scripts/master/webhooks/discord_github.sh
          chmod +x discord_github.sh
          ./discord_github.sh success
      - name: Error
        if: ${{failure()}}
        run: |
          wget https://raw.githubusercontent.com/chronoDave/user-scripts/master/webhooks/discord_github.sh
          chmod +x discord_github.sh
          ./discord_github.sh failure
